/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer_Billing;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Color;

import java.text.*;
import java.awt.print.*;
import javafx.print.Printer;
import javax.swing.JTextField;
import java.util.Calendar;
/**
 *
 * @author airvi
 */
public class CustomerBilling extends javax.swing.JFrame {
    String iTax, iSubtotal, iTotal;
    int n;
    double [] itemcost = new double [20];
    /**
     * Creates new form CustomerBilling
     */
    public CustomerBilling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtCustomerRef = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jtxtMobile = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCobRmType = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jCobNationality = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jCobID = new javax.swing.JComboBox<>();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jCobGender = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jCobMeal = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        saltedCupcake = new javax.swing.JCheckBox();
        vanillaCupcake = new javax.swing.JCheckBox();
        chocolateCupcake = new javax.swing.JCheckBox();
        lemonCupcake = new javax.swing.JCheckBox();
        limeCupcake = new javax.swing.JCheckBox();
        smoresCupcake = new javax.swing.JCheckBox();
        rainbowCupcake = new javax.swing.JCheckBox();
        strawberryCupcake = new javax.swing.JCheckBox();
        txtLemon = new javax.swing.JTextField();
        txtVanilla = new javax.swing.JTextField();
        txtChocolate = new javax.swing.JTextField();
        txtSalted = new javax.swing.JTextField();
        txtStrawberry = new javax.swing.JTextField();
        txtRainbow = new javax.swing.JTextField();
        txtSmores = new javax.swing.JTextField();
        txtLime = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubtotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(176, 224, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 224, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Customer_Ref:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jtxtCustomerRef.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jtxtCustomerRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustomerRefActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 200, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 200, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setText("Firstname:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("Lastname:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel1.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jtxtLastname.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel1.add(jtxtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel1.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, -1));

        jtxtMobile.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jtxtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMobileActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 200, -1));
        jPanel1.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setText("Customer Mobile:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setText("Nationality:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setText("Check Out Date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jCobRmType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Single", "Double", "Suite", "Penthouse" }));
        jPanel1.add(jCobRmType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 200, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setText("Date of Birth:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jCobNationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "British", "Irish", "Italian", "Greek", "Czech", "Unselected", " " }));
        jPanel1.add(jCobNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 200, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel11.setText("ID Type:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jCobID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ID Type", "Guest", "Employee" }));
        jCobID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCobIDActionPerformed(evt);
            }
        });
        jPanel1.add(jCobID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 200, 30));
        jPanel1.add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 200, 30));
        jPanel1.add(jDateChooser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel12.setText("Room Type:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jCobGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(jCobGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 200, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel14.setText("Gender:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jCobMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Meal", "Breakfast", "Lunch", "Dinner", "Room Service" }));
        jPanel1.add(jCobMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 200, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel15.setText("Meal:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel16.setText("Check In Date:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jPanel6.setBackground(new java.awt.Color(176, 224, 230));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 160, 50));

        jPanel7.setBackground(new java.awt.Color(176, 224, 230));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton9.setText("Exit");
        jPanel7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, 40));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton10.setText("Total");
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 40));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton11.setText("Reset");
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 80, 40));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 300, 120));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton7.setText("Total");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 420, 90));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 460, 700));

        jPanel3.setBackground(new java.awt.Color(176, 224, 230));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 500));

        jPanel8.setBackground(new java.awt.Color(176, 224, 230));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 60));

        jPanel9.setBackground(new java.awt.Color(176, 224, 230));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton13.setText("Exit");
        jPanel9.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, 40));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton14.setText("Total");
        jPanel9.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 40));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton15.setText("Reset");
        jPanel9.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 80, 40));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 300, 120));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 60));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 320, 140));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 370, 700));

        jPanel4.setBackground(new java.awt.Color(176, 224, 230));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(176, 224, 230));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(99, 169, 236)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saltedCupcake.setBackground(new java.awt.Color(176, 224, 230));
        saltedCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saltedCupcake.setText("Salted Caramel Cupcake");
        saltedCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saltedCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(saltedCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        vanillaCupcake.setBackground(new java.awt.Color(176, 224, 230));
        vanillaCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vanillaCupcake.setText("Vanilla Cupcake");
        vanillaCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanillaCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(vanillaCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        chocolateCupcake.setBackground(new java.awt.Color(176, 224, 230));
        chocolateCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chocolateCupcake.setText("Chocolate Cupcake");
        chocolateCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(chocolateCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lemonCupcake.setBackground(new java.awt.Color(176, 224, 230));
        lemonCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lemonCupcake.setText("Lemon Cupcake");
        lemonCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(lemonCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        limeCupcake.setBackground(new java.awt.Color(176, 224, 230));
        limeCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        limeCupcake.setText("Lime Coconut Cupcake");
        limeCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limeCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(limeCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        smoresCupcake.setBackground(new java.awt.Color(176, 224, 230));
        smoresCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        smoresCupcake.setText("Smore's Cupcake");
        smoresCupcake.setActionCommand("Smore's Cupcake");
        smoresCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smoresCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(smoresCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        rainbowCupcake.setBackground(new java.awt.Color(176, 224, 230));
        rainbowCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rainbowCupcake.setText("Rainbow Cupcake");
        rainbowCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainbowCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(rainbowCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        strawberryCupcake.setBackground(new java.awt.Color(176, 224, 230));
        strawberryCupcake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        strawberryCupcake.setText("Strawberry Cupcake");
        strawberryCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryCupcakeActionPerformed(evt);
            }
        });
        jPanel5.add(strawberryCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtLemon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLemon.setText("0");
        jPanel5.add(txtLemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 60, -1));

        txtVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVanilla.setText("0");
        txtVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVanillaActionPerformed(evt);
            }
        });
        jPanel5.add(txtVanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 60, -1));

        txtChocolate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChocolate.setText("0");
        jPanel5.add(txtChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 60, -1));

        txtSalted.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalted.setText("0");
        jPanel5.add(txtSalted, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 60, -1));

        txtStrawberry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStrawberry.setText("0");
        jPanel5.add(txtStrawberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 60, -1));

        txtRainbow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRainbow.setText("0");
        jPanel5.add(txtRainbow, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 60, -1));

        txtSmores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSmores.setText("0");
        jPanel5.add(txtSmores, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 60, -1));

        txtLime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLime.setText("0");
        jPanel5.add(txtLime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 60, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 310, 460));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel13.setText("Total Cost:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel17.setText("Tax Paid:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel18.setText("Subtotal:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jtxtTotal.setBackground(new java.awt.Color(176, 224, 230));
        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotal.setText("0");
        jtxtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 80, 40));

        jtxtTax.setBackground(new java.awt.Color(176, 224, 230));
        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTax.setText("0");
        jtxtTax.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 80, 40));

        jtxtSubtotal.setBackground(new java.awt.Color(176, 224, 230));
        jtxtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSubtotal.setText("0");
        jtxtSubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jtxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 80, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 370, 700));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1270, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCustomerRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustomerRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustomerRefActionPerformed

    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstnameActionPerformed

    private void vanillaCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanillaCupcakeActionPerformed
        if (vanillaCupcake.isSelected()) {
           txtVanilla.setEnabled(true);
           txtVanilla.setText("1");
           txtVanilla.requestFocus();
        } else {
            txtVanilla.setEnabled(false);
            txtVanilla.setText("0");
        }
    }//GEN-LAST:event_vanillaCupcakeActionPerformed

    private void saltedCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltedCupcakeActionPerformed
        // TODO add your handling code here:
        if (saltedCupcake.isSelected()) {
           txtSalted.setEnabled(true);
           txtSalted.setText("1");
           txtSalted.requestFocus();
        } else {
            txtSalted.setEnabled(false);
            txtSalted.setText("0");
        }
    }//GEN-LAST:event_saltedCupcakeActionPerformed

    private void strawberryCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryCupcakeActionPerformed
        // TODO add your handling code here:
        if (strawberryCupcake.isSelected()) {
           txtStrawberry.setEnabled(true);
           txtStrawberry.setText("1");
           txtStrawberry.requestFocus();
        } else {
            txtStrawberry.setEnabled(false);
            txtStrawberry.setText("0");
        }
    }//GEN-LAST:event_strawberryCupcakeActionPerformed

    private void limeCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limeCupcakeActionPerformed
        // TODO add your handling code here:
        if (limeCupcake.isSelected()) {
           txtLime.setEnabled(true);
           txtLime.setText("1");
           txtLime.requestFocus();
        } else {
            txtLime.setEnabled(false);
            txtLime.setText("0");
        }
    }//GEN-LAST:event_limeCupcakeActionPerformed
    private JFrame frame;
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Customer Billing System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        txtVanilla.setEnabled(false);
        txtChocolate.setEnabled(false);
        txtLemon.setEnabled(false);
        txtSalted.setEnabled(false);
        txtStrawberry.setEnabled(false);
        txtRainbow.setEnabled(false);
        txtSmores.setEnabled(false);
        txtLime.setEnabled(false);
        
        
        jtxtCustomerRef.setEnabled(false);
        //generate random customer reference number
        int refs = 5015 + (int) (Math.random()*17118);
        String cRef = "";
        cRef += refs + 1560;
        
        jtxtCustomerRef.setText(cRef);
        jtxtFirstname.setText(null);
        jtxtLastname.setText(null);
        jtxtAddress.setText(null);
        jtxtEmail.setText(null);
        jtxtMobile.setText(null);  
        jCobMeal.setSelectedIndex(0);
        jCobRmType.setSelectedIndex(0);
        //check-in date
        jDateChooser5.setDate(null);   
        //check-out date
        jDateChooser3.setDate(null);
        //date of birth
        jDateChooser4.setDate(null);
        
        jtxtTax.setText(" ");
        jtxtSubtotal.setText(" ");
        jtxtTotal.setText(" ");
        
        
                
        
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jtxtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMobileActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed

        txtVanilla.setText("0");
        txtChocolate.setText("0");
        txtLemon.setText("0");
        txtSalted.setText("0");
        txtStrawberry.setText("0");
        txtRainbow.setText("0");
        txtSmores.setText("0");
        txtLime.setText("0");
        
        txtVanilla.setEnabled(false);
        txtChocolate.setEnabled(false);
        txtLemon.setEnabled(false);
        txtSalted.setEnabled(false);
        txtStrawberry.setEnabled(false);
        txtRainbow.setEnabled(false);
        txtSmores.setEnabled(false);
        txtLime.setEnabled(false);
        
        vanillaCupcake.setSelected(false);
        chocolateCupcake.setSelected(false);
        lemonCupcake.setSelected(false);
        saltedCupcake.setSelected(false);
        strawberryCupcake.setSelected(false);
        rainbowCupcake.setSelected(false);
        smoresCupcake.setSelected(false);
        limeCupcake.setSelected(false);
        
        jtxtCustomerRef.setEnabled(false);
        //generate random customer reference number
        int refs = 5015 + (int) (Math.random()*17118);
        String cRef = "";
        cRef += refs + 1560;
        
        jtxtCustomerRef.setText(cRef);
        jtxtFirstname.setText(null);
        jtxtLastname.setText(null);
        jtxtAddress.setText(null);
        jtxtEmail.setText(null);
        jtxtMobile.setText(null);  
        jCobMeal.setSelectedIndex(0);
        jCobRmType.setSelectedIndex(0);
        //check-in date
        jDateChooser5.setDate(null);   
        //check-out date
        jDateChooser3.setDate(null);
        //date of birth
        jDateChooser4.setDate(null);
        
        jtxtTax.setText(" ");
        jtxtSubtotal.setText(" ");
        jtxtTotal.setText(" ");
        
        jtxtReceipt.setText(" ");
        
       
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        try{
            jtxtReceipt.print();
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void txtVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVanillaActionPerformed
        //txtVanilla.action(vanillaCupcake., n++);
    }//GEN-LAST:event_txtVanillaActionPerformed

    private void chocolateCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateCupcakeActionPerformed
        // TODO add your handling code here:
        if (chocolateCupcake.isSelected()) {
           txtChocolate.setEnabled(true);
           txtChocolate.setText("1");
           txtChocolate.requestFocus();
        } else {
            txtChocolate.setEnabled(false);
            txtChocolate.setText("0");
        }
    }//GEN-LAST:event_chocolateCupcakeActionPerformed

    private void rainbowCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rainbowCupcakeActionPerformed
        // TODO add your handling code here:
        if (rainbowCupcake.isSelected()) {
           txtRainbow.setEnabled(true);
           txtRainbow.setText("1");
           txtRainbow.requestFocus();
        } else {
            txtRainbow.setEnabled(false);
            txtRainbow.setText("0");
        }
    }//GEN-LAST:event_rainbowCupcakeActionPerformed

    private void smoresCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smoresCupcakeActionPerformed
        // TODO add your handling code here:
        if (smoresCupcake.isSelected()) {
           txtSmores.setEnabled(true);
           txtSmores.setText("1");
           txtSmores.requestFocus();
        } else {
            txtSmores.setEnabled(false);
            txtSmores.setText("0");
        }
    }//GEN-LAST:event_smoresCupcakeActionPerformed

    private void lemonCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonCupcakeActionPerformed
        // TODO add your handling code here:
        //need to decide if want user to be able to edit number cupcakes
        if (lemonCupcake.isSelected()) {
           txtLemon.setEnabled(true);
           txtLemon.setText("1");
           txtLemon.requestFocus();
        } else {
            txtLemon.setEnabled(false);
            txtLemon.setText("0");
        }
    }//GEN-LAST:event_lemonCupcakeActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // get total for items selected by user
        itemcost[0]= Double.parseDouble(txtVanilla.getText()) * 1.50;
        itemcost[1]= Double.parseDouble(txtChocolate.getText()) * 1.70;
        itemcost[2]= Double.parseDouble(txtLemon.getText()) * 1.75;
        itemcost[3]= Double.parseDouble(txtSalted.getText()) * 1.68;
        itemcost[4]= Double.parseDouble(txtStrawberry.getText()) * 1.10;
        itemcost[5]= Double.parseDouble(txtRainbow.getText()) * 2.64;
        itemcost[6]= Double.parseDouble(txtSmores.getText()) * 2.00;
        itemcost[7]= Double.parseDouble(txtLime.getText()) * 2.40;  
        
        itemcost[8] = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] + 
                itemcost[4] + itemcost[5] + itemcost[6] + itemcost[7];
        
        iTax = String.format("$ %.2f", itemcost[8]/100);
        iSubtotal = String.format("$ %.2f", itemcost[8]);
        iTotal = String.format("$ %.2f", itemcost[8] + (itemcost[8]/100)); 
        
        jtxtTax.setText(iTax);
        jtxtSubtotal.setText(iSubtotal);
        jtxtTotal.setText(iTotal);
        
        //=====================================================================
        jtxtReceipt.setEnabled(true);
        
        int refs = 1325 + (int) (Math.random()*4238);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("MMM-dd-yyyy");
        Tdate.format(timer.getTime());
        
        jtxtReceipt.append("\tCustomer Billing Systems\n" +
                "Reference:\t\t\t" + refs +
                "\n=============================================\t" +
                        
                "\n=============================================\t" +
                "\nCustomer Ref: " + jtxtCustomerRef.getText() +
                "\nCustomer Name: " + jtxtFirstname.getText() + " " + jtxtLastname.getText() +
                "\nVanilla Cupcake:\t\t" + txtVanilla.getText() +
                "\nChocolate Cupcake:\t\t" + txtChocolate.getText() +
                "\nLemon Cupcake:\t\t" + txtLemon.getText() +
                "\nSalted Caramel Cupcake:\t\t" + txtSalted.getText() +
                "\nStrawberry Cupcake:\t\t" + txtStrawberry.getText() +
                "\nRainbow Cupcake:\t\t" + txtRainbow.getText() +
                "\nSmore's Cupcake:\t\t" + txtSmores.getText() +
                "\nLime Coconut Cupcake:\t\t" + txtLime.getText() +
                
                "\nTax:\t\t\t" + iTax +
                "\nSubtotal:\t\t\t" + iSubtotal +
                "\nTotal:\t\t\t" + iTotal +
                "\n=============================================\t" + 
                "\nDate: " + Tdate.format(timer.getTime()) + 
                    "\tTime: " + tTime.format(timer.getTime()) +
                    "\n\n\tThank you for shopping at Cupcake Hotel\n");      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCobIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCobIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCobIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chocolateCupcake;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCobGender;
    private javax.swing.JComboBox<String> jCobID;
    private javax.swing.JComboBox<String> jCobMeal;
    private javax.swing.JComboBox<String> jCobNationality;
    private javax.swing.JComboBox<String> jCobRmType;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCustomerRef;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JCheckBox lemonCupcake;
    private javax.swing.JCheckBox limeCupcake;
    private javax.swing.JCheckBox rainbowCupcake;
    private javax.swing.JCheckBox saltedCupcake;
    private javax.swing.JCheckBox smoresCupcake;
    private javax.swing.JCheckBox strawberryCupcake;
    private javax.swing.JTextField txtChocolate;
    private javax.swing.JTextField txtLemon;
    private javax.swing.JTextField txtLime;
    private javax.swing.JTextField txtRainbow;
    private javax.swing.JTextField txtSalted;
    private javax.swing.JTextField txtSmores;
    private javax.swing.JTextField txtStrawberry;
    private javax.swing.JTextField txtVanilla;
    private javax.swing.JCheckBox vanillaCupcake;
    // End of variables declaration//GEN-END:variables
}
